name: rs_tools-env
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - jupyter
  - xlrd
  - openpyxl
  - rasterio
  - python-dotenv
  - ipyleaflet
  - rioxarray
  - sentinelsat
  - joblib
  - contextily
  - scikit-learn
  - opencv
  - python=3.8
  - dvc
  - pylint

