"""SingleRasterDownloader for all providers supported by eodag.

In particular, this downloader can be used to obtain Sentinel-2 L2A
data.
"""

from __future__ import annotations

import logging
from datetime import date, datetime
from pathlib import Path
from typing import Any, Literal, Optional, Union

import eodag
import pandas as pd
import shapely
from eodag import EODataAccessGateway
from eodag.api.search_result import SearchResult
from pydantic import Field, PrivateAttr
from shapely.geometry import Polygon

from geographer.downloaders.base_downloader_for_single_vector import (
    RasterDownloaderForSingleVector,
)
from geographer.errors import NoRastersForVectorFoundError
from geographer.global_constants import DUMMY_VALUE

log = logging.getLogger(__name__)


class SearchKwargs(dict):
    """Keyword arguments for the `search_all` method of an EODataAccessGateway.

    Note:
        The `geom` kwarg of the EODataAccessGateway.search_all method is
        omitted, because its value is determined as a `geographer` argument.

        See See https://eodag.readthedocs.io/en/latest/api_reference/core.html#eodag.api.core.EODataAccessGateway.search_all. # noqa
        for more details on most of the arguments below.

    This dictionary may include the following keys:
    - `start` (Optional[str]):
        Start sensing time in ISO 8601 format (e.g. “1990-11-26”,
        “1990-11-26T14:30:10.153Z”, “1990-11-26T14:30:10+02:00”, …).
        If no time offset is given, the time is assumed to be given in UTC.
    - `end` (Optional[str]):
        End sensing time in ISO 8601 format (e.g. “1990-11-26”,
        “1990-11-26T14:30:10.153Z”, “1990-11-26T14:30:10+02:00”, …).
        If no time offset is given, the time is assumed to be given in UTC.
    - `provider` (Optional[str]):
        The provider to be used. If set, search fallback will be disabled.
        If not set, the configured preferred provider will be used at first
        before trying others until finding results. See
        https://eodag.readthedocs.io/en/stable/_modules/eodag/api/core.html#EODataAccessGateway.search. # noqa
    - `items_per_page` (Optional[int]):
        Number of items to retrieve per page.
    - `locations` (Optional[dict[str, str]]):
        Location filtering by name using locations configuration
        {"<location_name>"="<attr_regex>"}. For example, {"country"="PA."}
        will use the geometry of the features having the property ISO3 starting
        with 'PA' such as Panama and Pakistan in the shapefile configured with
        name=country and attr=ISO3.
    - `**kwargs` (dict[str, Any]):
        Any other search parameters compatible with the provider.
    """

    pass


class DownloadKwargs(dict):
    """Kwyword arguments for the `download` method of an EOProduct.

    Refer to the EOProduct documentation for more details:
    https://eodag.readthedocs.io/en/stable/api_reference/eoproduct.html#
    TODO render as link...

    Warning:
        - `output_extension`: No guarantee that `geographer` will work if
            you set this value.

    Some kwargs of the EOProduct.download method should not be used:
        - `product`: Omitted because the value is determined by `geographer`.
        - `progress_callback`: Omitted because its values cannot easily
            be JSON serialized.
        - `extract`: Omitted because geographer requires the value of this
            kwarg to be True.
        - `output_dir`: Omitted because the value is determined by `geographer`.
        - `asset`: Omitted because it does not make sense for a downloader
            for a single vector.

    This dictionary may include any of the following keys:
    - `wait` (int): The wait time in minutes between two download attempts.
    - `timeout` (int): The max time in minutes to retry downloading before stopping.
    - `dl_url_params` (dict[str, str]): Additional URL parameters to pass to
        the download URL.
    - `delete_archive` (bool): Whether to delete the downloaded archives
        after extraction.
    - `output_extension`: (str) If you don't want to use the default you should
        know what you are doing.
    """

    pass


FORBIDDEN_DOWNLOAD_KWARGS_KEYS = [
    "product",
    "progress_callback",
    "extract",
    "output_dir",
    "asset",
]


ASC_OR_DESC = Literal["ASC", "DESC"]
ASC_OR_DESC_VALUES = ["ASC", "DESC"]


# TODO Used to be SentinelDownloaderForSingleVector replace/adapt all references
# TODO Make all links render properly in the autogenerated docs
class EodagDownloaderForSingleVector(RasterDownloaderForSingleVector):
    """Downloader for providers supported by eodag.

    Refer to the eodag documentation at
    https://eodag.readthedocs.io/en/stable/
    for more details on eodag.
    """

    eodag_kwargs: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Optional kwargs defining an EODataAccessGateway instance. "
            "Possible keys are 'user_conf_file_path' to define a Path to "
            "the user configuration file and locations_conf_path to define "
            "a Path to the locations configuration file. "
            "See https://eodag.readthedocs.io/en/stable/api_reference/core.html#eodag.api.core.EODataAccessGateway."  # noqa
        ),
    )

    eodag_setup_logging_kwargs: dict[str, Any] = Field(
        default_factory=lambda: dict(verbose=1),
        description=(
            "Kwargs to be passed to eodag.utils.logging.setup_logging "
            "to set up eodag logging. See "
            "https://eodag.readthedocs.io/en/stable/api_reference/utils.html#eodag.utils.logging.setup_logging"  # noqa
        ),
    )

    # Note that eodag as is not defined as a field.
    # This is so the pydantic fields are json serializable.
    _eodag: EODataAccessGateway = PrivateAttr()

    def model_post_init(self, __context):
        """Perform additional initialization."""
        eodag.setup_logging(**self.eodag_setup_logging_kwargs)

        self._eodag = EODataAccessGateway(**self.eodag_kwargs)

    @property
    def eodag(self) -> EODataAccessGateway:
        """Get eodag."""
        return self._eodag

    def download(  # type: ignore
        self,
        vector_name: Union[str, int],
        vector_geom: Polygon,
        download_dir: Path,
        previously_downloaded_rasters_set: set[str],
        id_field: str,
        search_kwargs: Optional[SearchKwargs] = None,
        download_kwargs: Optional[DownloadKwargs] = None,
        properties_to_save: Optional[list[str]] = None,
        filter_property: Optional[Union[dict[str, Any], list[dict[str, Any]]]] = None,
        filter_online: bool = True,
        sort_by: Optional[list[tuple[str, ASC_OR_DESC]]] = None,
        **kwargs,
    ) -> dict:
        """Download a raster for a vector featureusing eodag.

        Download a raster fully containing the vector feature,
        returns a dict in the format needed by the associator.

        Warning:
            It is _very important_ that the correct value for the id_field argument
            is passed (see below for a description of the argument). The download method
            and the connector will not work properly if this is not the case!

        Note:
            The start, end, provider, items_per_page, and locations arguments correspond
            to kwargs of EODataAccessGateway.search_all (though the provider kwarg is only
            documented for the EODataAccessGateway.search). The descriptions are adapted
            from the official eodag documentation at
            https://eodag.readthedocs.io/en/latest/api_reference/core.html#eodag.api.core.EODataAccessGateway.

        Args:
            vector_name:
                name of vector feature
            vector_geom:
                Geometry of vector feature
            download_dir:
                Directory Sentinel-2 products will be downloaded to.
            previously_downloaded_rasters_set:
                Set of already downloaded products.
            id_field:
                Key for which the corresponding value in the properties dict
                of an eodag.api.product._product.EOProduct defines (the stem of, i.e.
                without the ".tif" suffix) the raster file name. For S2_MSI_L2A
                products this should be 'id' and this probably works for most other
                products as well.
            search_kwargs:
                Keyword arguments for the `search_all` method of an EODataAccessGateway,
                excluding "geom". Refer to the docstring of SearchKwargs for more details.
            download_kwargs:
                Keyword arguments for the download` method of an EOProduct, excluding
                certain keys. Refer to the docstring of DownloadKwargs for more details.
            properties_to_save:
                List of property keys to extract and save from an EOProduct's
                properties dictionary. Values that cannot be stored in a
                GeoDataFrame will be replaced with the string "__DUMMY_VALUE__".
            filter_property:
                Kwargs or list of kwargs defining criteria according to which products
                should be filtered. These correspond exactly to kwargs for the
                EODataAccessGateway.filter_property method. Refer to
                https://eodag.readthedocs.io/en/stable/plugins_reference/generated/eodag.plugins.crunch.filter_property.FilterProperty.html#eodag.plugins.crunch.filter_property.FilterProperty  # noqa
                for more details.
            filter_online:
                Whether to filter the results for products that are online.
            sort_by:
                (optional) Tuple like ("key", "ASC"|"DESC") by which to sort the results.
            **kwargs: Other criteria that will be used in the search, using
                parameters compatible with the provider.

        Returns:
            A dictionary containing information about the rasters.
            ({'list_raster_info_dicts': [raster_info_dict]})

        Raises:
            ValueError: Raised if an unkknown product type is given.
            NoRastersForPolygonFoundError: Raised if no downloadable rasters
            could be found for the vector feature.
        """
        search_kwargs = search_kwargs or {}
        download_kwargs = download_kwargs or {}
        properties_to_save = properties_to_save or []
        filter_property = filter_property or {}
        if isinstance(filter_property, dict):
            filter_property = [filter_property]
        sort_by = sort_by or []
        if isinstance(sort_by, tuple):
            sort_by = [sort_by]

        self._validate_download_args(download_kwargs=download_kwargs, sort_by=sort_by)

        search_criteria = search_kwargs | {
            "geom": vector_geom,
        }

        result: SearchResult = self.eodag.search_all(**search_criteria)

        # TODO will this work when no raster contains the geometry?
        # Only keep results that contain the geometry
        result.filter_overlap(geometry=vector_geom, contains=True)

        for filter_kwargs in filter_property:
            result.filter_property(**filter_kwargs)

        if filter_online:
            result.filter_online()

        if len(result) == 0:
            raise NoRastersForVectorFoundError(
                f"No rasters for vector feature {vector_name} found with "
                f"search criteria {search_criteria}!"
            )

        if sort_by:
            # Currently only support sorting by a single key.
            # In the future, we may implement hierarchical
            # sorting by multiple keys.
            key, asc_or_desc = sort_by[0]
            reverse = {"ASC": False, "DESC": True}.get(asc_or_desc)
            result = SearchResult(
                products=sorted(
                    result, key=lambda product: product.properties[key], reverse=reverse
                ),
                number_matched=result.number_matched,
                errors=result.errors,
            )

        # Return dicts with values to be collected in calling associator.
        raster_info_dict = {}

        for eo_product in result:
            raster_name = eo_product.properties[id_field] + ".tif"

            if raster_name not in previously_downloaded_rasters_set:

                download_params = download_kwargs | dict(
                    product=eo_product,
                    output_dir=download_dir,
                    extract=True,
                )

                try:
                    location = self.eodag.download(**download_params)

                    location_stem = Path(location).stem
                    if location_stem != raster_name:
                        log.warning(
                            "The raster_name (%s) does not agree with the stem "
                            "of the downloaded file (%s). The downloder will "
                            "not recognize which files have already been downloaded, "
                            "and the connector will not work properly!",
                            raster_name,
                            location_stem,
                        )

                    # And assemble the information to be updated
                    # in the returned raster_info_dict:
                    properties_to_save_dict = {}
                    for key in properties_to_save:
                        if key in eo_product.properties:
                            val = eo_product.properties.get(key)
                            definitely_accepted_types = (
                                str,
                                int,
                                float,
                                type(None),
                                date,
                                datetime,
                                shapely.geometry.base.BaseGeometry,
                            )
                            if not isinstance(val, definitely_accepted_types):
                                try:
                                    pd.Series([val])
                                except (TypeError, ValueError):
                                    val = DUMMY_VALUE
                            properties_to_save_dict[key] = val
                    raster_info_dict.update(properties_to_save_dict)
                    raster_info_dict["raster_name"] = raster_name
                    raster_info_dict["raster_processed?"] = False

                    return {"list_raster_info_dicts": [raster_info_dict]}

                except Exception as exc:
                    log.warning(
                        "Failed to download, extract, or process %s: %s",
                        eo_product,
                        str(exc),
                    )

        raise NoRastersForVectorFoundError(
            f"All rasters for {vector_name} failed to download."
        )

    def _validate_download_args(self, download_kwargs: DownloadKwargs, sort_by: list):
        """Validate download arguments."""
        for key in download_kwargs:
            if key in FORBIDDEN_DOWNLOAD_KWARGS_KEYS:
                msg = "The key '%s' is forbidden and cannot be used."
                log.error(msg, key)
                raise ValueError(msg % key)

        for key, asc_or_desc in sort_by:
            if asc_or_desc not in ASC_OR_DESC_VALUES:
                msg = (
                    "Found %s as second entry of a sort_by pair. "
                    "Must be one of 'ASC' or 'DESC'!"
                )
                log.error(msg, asc_or_desc)
                raise ValueError(msg % asc_or_desc)

        if len(sort_by) > 1:
            msg = (
                "At the moment sorting is only supported for a single key at a time. "
                "The length of the sort_by list must be at most 1."
            )
            log.error(msg)
            raise ValueError(msg)


# TODO remove before merging - for testing purposes
if __name__ == "__main__":
    import pydantic

    print(f"pydantic version: {pydantic.__version__}")

    downloader = EodagDownloaderForSingleVector()

    downloader.download(
        "vector_name",
        vector_geom=Polygon(
            [[3.2, 44.4], [3.7, 44.4], [3.7, 44.9], [3.2, 44.9], [3.2, 44.4]]
        ),  # small_geom from EODAG 6_crunch notebook
        download_dir=Path("/home/rustam/dida/geographer/GeoGrapher/TEMP"),
        previously_downloaded_rasters_set=set(),
        id_field="id",
        search_kwargs=SearchKwargs(
            start="2021-03-01",
            end="2021-03-31",
            provider="cop_dataspace",
            productType="S2_MSI_L2A",
        ),
        sort_by=[("cloudCover", "ASC")],
    )
