name: Lint and test

on: [push]

env:
  PIP_PROGRESS_BAR: "off"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        make venv
    - name: Run linters
      run: |
        make lint
    - name: Run tests
      run: |
        make test
